<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>API de libros · Laravel + MongoDB</title>
<style>body{font:16px system-ui;margin:0;background:#eef3f8;color:#172c45}main{max-width:1100px;margin:auto;padding:38px}small{color:#287970;font-weight:700;letter-spacing:2px}h1{font-size:38px;margin:12px 0}p{line-height:1.6}button{background:#087e74;color:white;padding:14px 24px;border:0;border-radius:8px;font-weight:bold;cursor:pointer}#results{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:24px}article{background:white;border:1px solid #d5e0ea;border-radius:12px;padding:20px;min-width:0}h2{font-size:18px;margin:0 0 12px}pre{font-size:13px;white-space:pre-wrap;overflow-wrap:anywhere;background:#f2f6fa;padding:12px;border-radius:6px;line-height:1.45}strong{color:#087e74}a{color:#087e74}.meta{color:#546980}</style>
<main><small>PRÁCTICA · APLICACIONES WEB FRONTEND NOSQL</small><h1>API de libros</h1><p class="meta">Laravel 13 · MongoDB · Meza Corella César<br>Docente: Roldán Aquino Segura</p><p>Prueba real de las rutas HTTP. Se crea un libro de demostración y se elimina al terminar.<br>Conexión local configurada en <code>.env</code> · Base de datos <code>api_libros</code></p><button id="run">Ejecutar pruebas CRUD</button> <span id="state">Listo para probar</span><div id="results"></div><p><a href="https://github.com/YvnPretty/rest">Código fuente en GitHub</a></p></main>
<script>
window.evidence=[];
document.querySelector('#run').onclick=async()=>{
const button=document.querySelector('#run');button.disabled=true;document.querySelector('#results').replaceChildren();window.evidence=[];
async function call(label,method,path,body,expected){const r=await fetch(path,{method,headers:{'Accept':'application/json','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}const item={label,method,path,request:body??null,status:r.status,expected,response:data};window.evidence.push(item);const card=document.createElement('article');const h=document.createElement('h2');h.textContent=label+' · HTTP '+r.status;const pre=document.createElement('pre');pre.textContent=method+' '+path+'\n\n'+(text?JSON.stringify(data,null,2):'(respuesta vacía)');card.append(h,pre);document.querySelector('#results').append(card);if(r.status!==expected)throw Error('Estado inesperado: '+r.status);return data;}
try{const book=await call('1. Crear libro','POST','/api/libros',{titulo:'Don Quijote',autor:'Miguel de Cervantes',genero:'Novela',anio_publicacion:1605},201);await call('2. Listar libros','GET','/api/libros',null,200);await call('3. Consultar libro','GET','/api/libros/'+book.id,null,200);await call('4. Actualizar título','PUT','/api/libros/'+book.id,{titulo:'Don Quijote de la Mancha'},200);await call('5. Eliminar libro','DELETE','/api/libros/'+book.id,null,204);await call('6. Consultar eliminado','GET','/api/libros/'+book.id,null,404);await call('7. Validar campos','POST','/api/libros',{},422);document.querySelector('#state').textContent='7/7 pruebas correctas';}catch(e){document.querySelector('#state').textContent='Error: '+e.message;}finally{button.disabled=false;window.done=true;}};
</script></html>
